version: 2
jobs:
  build:
    docker:
      - image: node:11
    environment:
      - APP_ID: miepjgfkkommhllbbjaedffcpkncboeo
    steps:
      - checkout
      - run:
          name: 'Dependencies'
          command: |
            apt-get update
            apt-get -y install curl jq
            yarn
      - run:
          name: 'Build'
          command: yarn build
      - run:
          name: 'Test'
          command: yarn test
      - run:
          name: 'Package'
          command: git archive -o dyslexia-friendly.zip HEAD
